default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: plants_for_hire_development

test:
  <<: *default
  database: plants_for_hire_test

production:
  <<: *default
  database: plants_for_hire_production
  username: plants_for_hire
  password: <%= ENV['PLANTS_FOR_HIRE_DATABASE_PASSWORD']
